class selectors {
    
    static UserName = "#user-name"
    static Password = "#password"
    static LoginButton = "#login-button"
    static HomePageTitle = ".app_logo"
    static ErrorMessage = ".error-message-container.error h3"
    static Menu = "#react-burger-menu-btn"
    static LogoutButton = "#logout_sidebar_link"
    static LoginPageTitle = ".login_logo"
    static ProductList = ".inventory_item_name"
    static AddToCart = ".btn.btn_primary.btn_small.btn_inventory"
    static Cart = ".shopping_cart_link"
    static Checkout = "#checkout"
    static FirstName = "#first-name"
    static LastName = "#last-name"
    static ZipCode = "#postal-code"
    static ContinueButton = "#continue"
    static FinishButton = "#finish"
    static CheckoutBanner = ".complete-header"
    static Backpack = "#add-to-cart-sauce-labs-backpack"
    static Onesie = "#add-to-cart-sauce-labs-onesie"
    static BoltTShirt = "#add-to-cart-sauce-labs-bolt-t-shirt"
    static TotalPrice = ".summary_subtotal_label"
    static FinalPrice = ".summary_info_label.summary_total_label"
    static IndividualPrices = ".inventory_item_price"
    static SortOption = ".product_sort_container"
    static AddToCartNew = "button[data-test]"
    static CartBubbleNumber = ".shopping_cart_badge"
    static Footer = ".footer"
    static TwitterRedirect = ".social_twitter a"
    static FacebookRedirect = ".social_facebook a"
    static LinkedInRedirect = ".social_linkedin a"

}

module.exports = selectors